
Build:
	gcc main.c -o main
	
run:
	./main

	
buildtest1:
	gcc test/testcalculator/calculatorv1.c test/testcalculator/test_calculatorv1.c Unity/unity.c -Iunity -o test/testcalculator/testcalc.out
runtest1:
	./test/testcalculator/testcalc.out


buildtest2:
	gcc test/teststopwatch/stopwatchv1.c test/teststopwatch/test_stopwatchv1.c Unity/unity.c -Iunity -o test/teststopwatch/teststopw.out
runtest2:
	./test/teststopwatch/teststopw.out

	
buildtest3:
	gcc test/testvote/votev1.c test/testvote/test_votev1.c Unity/unity.c -Iunity -o test/testvote/testvote.out
runtest3:
	./test/testvote/testvote.out

	
buildtest4:
	gcc test/testsnake/unit_convertorv1.c test/testsnake/test_unit_convertorv1.c Unity/unity.c -Iunity -o test/testsnake/testsnake.out
runtest4:
	./test/testsnake/testsnake.out
